### ISSUE TITLE
coordination: master issue for project

### ISSUE THREAD

**Issue by skeptrunedev** [arguflow/royal-road-embeddings#19]
## Endpoint to index/re-index a given chapter

- [x] `handler` takes `doc_html`, `story_id`, and `doc_num`
- [x] `model` to track `story_id` + `doc_num` + `avg_embedding` + `qdrant_point_id` = `DocEmbedding`

### Delete previous embeddings for chapter

- [x] #24
- [x] `query` to remove filtered `DocEmbedding`'s from Qdrant

### Create new embeddings for chapter

- [x] segmentation script to break up `doc_html` into individual embeddings
- [x] `operator` to GPU to get `embedding` for segments in batch
- [x] #20
- [x] `query` to insert `DocEmbedding`'s' into Qdrant collection

## Endpoint to average/re-average for a given story id

- [x] #27
- [x] #29
- [x] #31
- [x] #33
- [x] #56
- [x] #44
- [x] #47

## Endpoint to recommend content 

Might be some edge-cases here for users who have crazy numbers of liked/favorited stories

- [x] #34
- [x] #39
- [x] #45

## Endpoint to semantically search

- [x] #35
- [x] `operator` to get embedding from GPU for `query_string`
- [x] `query` to Qdrant to get semantically similar results for the `query_string` for appropriate `doc_group_size`

## Endpoint for query vs. a single point

- [x] #49
- [x] #52
- [x] #53

I think we should change how the re-index on update works. 

### Changes required 

- [x] #57

### New logic to run when a chapter is re-indexed

- [x] get all of the group sizes which have been constructed 
- [x] #59
- [x] #61

### New logic to run when a chapter is indexed 

- get all of the group sizes which have been constructed 
- based on the `index` of the chapter, calculate `group` index which needs to be re-averaged or created 
- re-average or create requisite groups

**Comment by skeptrunedev** [comment]
I think we should change how the re-index on update works. 

### Changes required 

- track which groups have been created in Postgres

### New logic to run when a chapter is re-indexed

- get all of the group sizes which have been constructed 
- based on the `index` of the chapter, calculate `group` index which needs to be re-averaged
- re-average and update requisite groups 

### New logic to run when a chapter is indexed 

- get all of the group sizes which have been constructed 
- - based on the `index` of the chapter, calculate `group` index which needs to be re-averaged or created 
- re-average or create requisite groups
